const modernData = [
    {
        ques: "when vasco da gama came to india at calcut?",
        bop: "1494",
        aop: "1505",
        cop: "1509",
        ans: "1498",
},
{
    ques: "when 2nd time vasco da gama came to india?",
    bop: "1498",
    aop: "1505",
    cop: "1509",
    ans: "1501",
},
{
    ques: "when 3rd time vasco da gama came to india?",
    bop: "1498",
    aop: "1505",
    cop: "1509",
    ans: "1524",
},
{
    ques: "when francisco came to india?",
    bop: "1498",
    aop: "1506",
    cop: "1509",
    ans: "1505",
},
{
    ques: "when alfonso de albuquerque vasco da gama came to india?",
    bop: "1498",
    aop: "1505",
    cop: "1501",
    ans: "1509",
},
{
    ques: "when alfonso de albuquerque captured goa to ?",
    bop: "1498",
    aop: "1505",
    cop: "1511",
    ans: "1510",
},
{
    ques: "when 1st factory open?",
    bop: "1611",
    aop: "1602",
    cop: "1668",
    ans: "1605",
},
{
    ques: "when french open 1st factory open?",
    bop: "1611",
    aop: "1602",
    cop: "1605",
    ans: "1668",
},
{
    ques: "when britisher 1st temporary factory open?",
    bop: "1612",
    aop: "1602",
    cop: "1668",
    ans: "1611",
},
{
    ques: "when britisher 1st factory open?",
    bop: "1612",
    aop: "1602",
    cop: "1611",
    ans: "1613",
},
{
    ques: "where dutch open factory or 1st factory?",
    bop: "surat",
    aop: "calicut",
    cop: "goa",
    ans: "masulipatnam",
},
{
    ques: "where french open factory or 1st factory?",
    bop: "masulipatnam",
    aop: "calicut",
    cop: "goa",
    ans: "surat",
},
{
    ques: "where britisher open factory temporary 1st factory?",
    bop: "surat",
    aop: "calicut",
    cop: "goa",
    ans: "masulipatnam",
},
{
    ques: "where dutch open 1st factory?",
    bop: "masulipatnam",
    aop: "calicut",
    cop: "goa",
    ans: "surat",
},
{
    ques: "when east india company established?",
    bop: "1600",
    aop: "1598",
    cop: "1602",
    ans: "1599",
},
{
    ques: "when william hawkins came to jahangir court?",
    bop: "1609",
    aop: "1605",
    cop: "1615",
    ans: "1608",
},
{
    ques: "when thomas roe came to jahangir court?",
    bop: "1609",
    aop: "1605",
    cop: "1608",
    ans: "1615",
},
{
    ques: "when battle of swalley happen?",
    bop: "1609",
    aop: "1605",
    cop: "1615",
    ans: "1612",
},
{
    ques: "when battle of chinusurah/biddera/hoogly happen?",
    bop: "1760",
    aop: "1756",
    cop: "1758",
    ans: "1759",
},
{
    ques: "when william hawkins came to jahangir court?",
    bop: "1609",
    aop: "1605",
    cop: "1615",
    ans: "1608",
},
{
    ques: "when 1st carnatic wars happen?",
    bop: "1750-1752",
    aop: "1745-1746",
    cop: "1742-1744",
    ans: "1746-1748",
},
{
    ques: "when 2nd carnatic wars happen?",
    bop: "1750-1752",
    aop: "1745-1746",
    cop: "1749-1753",
    ans: "1749-1754",
},
{
    ques: "when 3rd carnatic wars happen?",
    bop: "1750-1752",
    aop: "1745-1746",
    cop: "1742-1744",
    ans: "1756-1763",
},
{
    ques: "when battle of wandiwash happen?",
    bop: "1750",
    aop: "1762",
    cop: "1764",
    ans: "1760",
},
{
    ques: "when battle of ambur wars happen?",
    bop: "1750-1752",
    aop: "1745-1746",
    cop: "1749-1753",
    ans: "1749-1754",
},
{
    ques: "when operation vijay start?",
    bop: "1972",
    aop: "1971",
    cop: "1965",
    ans: "1961",
},
{
    ques: "when sanyasi revolt happen?",
    bop: "1772",
    aop: "1766",
    cop: "1763",
    ans: "1764",
},
{
    ques: "when paika rebellion happen?",
    bop: "1820",
    aop: "1819",
    cop: "1818",
    ans: "1817",
},
{
    ques: "when ahom revolt happen?",
    bop: "1820",
    aop: "1819",
    cop: "1824",
    ans: "1828",
},
{
    ques: "when pagal panthi revolt happen?",
    bop: "1820",
    aop: "1819",
    cop: "1824",
    ans: "1825",
},
{
    ques: "when moplah uprising happen?",
    bop: "1820",
    aop: "1831",
    cop: "1834",
    ans: "1836",
},
{
    ques: "when kol mutiny happen?",
    bop: "1820",
    aop: "1836",
    cop: "1834",
    ans: "1831",
},
{
    ques: "when ho and munda uprising happen?",
    bop: "1887",
    aop: "1896",
    cop: "1895",
    ans: "1899",
},
{
    ques: "when birsa munda arrested?",
    bop: "1887",
    aop: "1899",
    cop: "1898",
    ans: "1895",
},
{
    ques: "where birsa munda born?",
    bop: "bengal,kolkata",
    aop: "assam",
    cop: "koderma,ranchi",
    ans: "ranchi,singhbum",
},
{
    ques: "when santhal rebellion happen?",
    bop: "1857",
    aop: "1859",
    cop: "1858",
    ans: "1855",
},
{
    ques: "when indigo revolt happen?",
    bop: "1887",
    aop: "1869",
    cop: "1858",
    ans: "1859",
},
{
    ques: "when brahmo samaj found?",
    bop: "1857",
    aop: "1839",
    cop: "1830",
    ans: "1828",
},
{
    ques: "when tattavabodhini samaj found?",
    bop: "1857",
    aop: "1831",
    cop: "1830",
    ans: "1839",
},
{
    ques: "when dhrama sabha found?",
    bop: "1857",
    aop: "1839",
    cop: "1828",
    ans: "1830",
},
{
    ques: "when paramhan mandali found?",
    bop: "1857",
    aop: "1839",
    cop: "1867",
    ans: "1849",
},
{
    ques: "when prathna samaj found?",
    bop: "1857",
    aop: "1839",
    cop: "1849",
    ans: "1867",
},
{
    ques: "when satayasodhak samaj found?",
    bop: "1871",
    aop: "1839",
    cop: "1872",
    ans: "1873",
},
{
    ques: "when arya samaj found?",
    bop: "1871",
    aop: "1839",
    cop: "1872",
    ans: "1875",
},
{
    ques: "when ramakrishan mission found?",
    bop: "1871",
    aop: "1898",
    cop: "1899",
    ans: "1897",
},
{
    ques: "when servant of indin society found?",
    bop: "1887",
    aop: "1908",
    cop: "1920",
    ans: "1905",
},
{
    ques: "when seva sadan found?",
    bop: "1887",
    aop: "1906",
    cop: "1920",
    ans: "1908",
},
{
    ques: "when social servie league found?",
    bop: "1887",
    aop: "1908",
    cop: "1921",
    ans: "1920",
},
{
    ques: "when indian national social conference found?",
    ans: "1887",
    aop: "1908",
    cop: "1920",
    bop: "1905",
},
{
    ques: "when theosophical society  found?",
    ans: "1875",
    aop: "1867",
    cop: "1890",
    bop: "1899",
},
{
    ques: "when first hindu college open in calcutta?",
    ans: "1817",
    aop: "1898",
    cop: "1895",
    bop: "1887",
},
{
    ques: "when first hindu college open in banaras?",
    ans: "1898",
    aop: "1817",
    cop: "1895",
    bop: "1887",
},
{
    ques: "when age of consent act came?",
    bop: "1887",
    aop: "1898",
    cop: "1895",
    ans: "1891",
},
{
    ques: "when young bengal movement start?",
    cop: "1887",
    aop: "1824",
    ans: "1820s",
    bop: "1828",
},
{
    ques: "who formed brhamo samaj?",
    ans: "raja ram mohan roy",
    aop: "debendranath tagore",
    cop: "radhakant deb",
    bop: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed tattvabodhini samaj?",
    aop: "raja ram mohan roy",
ans: "debendranath tagore",
    cop: "radhakant deb",
    bop: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed dhrama sabha?",
    cop: "raja ram mohan roy",
    aop: "debendranath tagore",
    ans: "radhakant deb",
    bop: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed paramahans mandali?",
    bop: "raja ram mohan roy",
    aop: "debendranath tagore",
    cop: "radhakant deb",
    ans: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed prathna samaj?",
    ans: "atmaram padurang",
    aop: "debendranath tagore",
    cop: "radhakant deb",
    bop: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed satyasodhak samaj?",
    ans: "jyotirao phule",
    aop: "debendranath tagore",
    cop: "radhakant deb",
    bop: "dadaram padurang and mehtaji durugram",
},
{
    ques: "who formed servant of indian society?",
    ans: "GK gokhale",
    aop: "N M joshi",
    cop: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed social service league?",
    aop: "GK gokhale",
    ans: "N M joshi",
    cop: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed seva sadan?",
    aop: "GK gokhale",
    cop: "N M joshi",
    ans: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed dev samaj?",
    ans: " S N angihotri",
    aop: "N M joshi",
    cop: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed indian national social conference?",
    aop: "GK gokhale",
    bop: "N M joshi",
    cop: "B M malabari",
    ans: "M G ranade  or raghunath rao",
},
{
    ques: "who formed theosopical society?",
    aop: "H P Blavastsky or M S olcott",
    ans: "N M joshi",
    cop: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed aligarh movement?",
    aop: "sir syed ahmed khan",
    ans: "N M joshi",
    cop: "B M malabari",
    bop: "M G ranade  or raghunath rao",
},
{
    ques: "who formed young bengal movement?",
    ans: "Henry vivian deroza",
    aop: "sarala devi chaudrani",
    cop: "B M malabari",
    bop: "ramabai ranade",
},
{
    ques: "who formed bharat stree movement?",
    aop: "Henry vivian deroza",
    ans: "sarala devi chaudrani",
    cop: "B M malabari",
    bop: "ramabai ranade",
},
{
    ques: "who formed ladies social conference",
    aop: "Henry vivian deroza",
    bop: "sarala devi chaudrani",
    cop: "B M malabari",
    ans: "ramabai ranade",
},
{
    ques: "who formed age of consent act?",
    aop: "Henry vivian deroza",
cop: "sarala devi chaudrani",
ans: "B M malabari",
    bop: "ramabai ranade",
},
{
    ques: "who gandhi born?",
    aop: "2 oct 1867",
    ans: "2 oct 1869",
    cop: "2 oct 1865",
    bop: "2 oct 1871",
},
{
    ques: "who gandhi came back to india?",
    aop: "9 jan 1914",
    ans: "9 jan 1915",
    cop: "9 jan 1917",
    bop: "9 jan 1918",
},
{
    ques: "who champaran satyagarh start?",
    aop: " 1914",
    ans: "1917",
    cop: " 1915",
    bop: "1918",
},
{
    ques: "who ahmedabad mill strike or kheda satyagarh start?",
    aop: " 1914",
    ans: "1918",
    cop: " 1917",
    bop: "1919",
},
{
    ques: "who formed communist party of india tashkatan, uzbekistan?",
    aop: " N M joshi",
    ans: "M N roy",
    cop: "joseph baptisto",
    bop: "S A Dange",
},
{
    ques: "when communist party of india formed",
    aop: " 1914",
    ans: "1920",
    cop: " 1925",
    bop: "1918",
},
{
    ques: "kanpur bolshevik conspiracy case?",
    aop: " 1914",
    ans: "1924",
    cop: " 1925",
    bop: "1918",
},
{
    ques: "all india trade union congress",
    aop: " 1914",
    ans: "1920",
    cop: " 1925",
    bop: "1918",
},
{
    ques: "when mahad satyagarh start",
    aop: " 1914",
    ans: "1927",
    cop: " 1925",
    bop: "1928",
},
{
    ques: "pathar dabi write by",
    aop: " sachin sanyal",
    ans: "sharat chandar chaterjee",
    cop: "B C Vohro",
    bop: "Surya Sen",
},
{
    ques: "bandi jiwan write by",
    ans: " sachin sanyal",
    aop: "sharat chandar chaterjee",
    cop: "B C Vohro",
    bop: "Surya Sen",
},
{
    ques: "philoshpy of bomb",
    aop: " sachin sanyal",
    cop: "sharat chandar chaterjee",
    ans: "B C Vohro",
    bop: "Surya Sen",
},
{
    ques: "when bhagat singh or sukhdev hanged",
    aop: "23 march 1930",
    ans: "23 march 1931",
    cop: "24 march 1931",
    bop:"21 march 1930",
},
{
    ques: "when bhagat singh or batukehswar dutt bomb in council of legislative assembly",
    aop: " 1930",
    ans: " 1929",
    cop: " 1931",
    bop:" 1930",
},
{
    ques: "when bhagat singh or sukhdev killed saunders",
    aop: "1927",
    ans: "1928",
    cop: "1931",
    bop:" 1930",
},
{
    ques: "when chittory arm raid happen",
    aop: "1930",
    ans: "1930",
    cop: "1931",
    bop:"1930",
},
{
    ques: "who did chittory arm raid",
    aop: "sachin sanyal",
    ans: "surya sen",
    cop: "B C vohro",
    bop:"bakteshwar dutt or chandrashekhar azad",
},
{
    ques: "when simon commission come to india",
    aop: "1932",
    ans: "1928",
    cop: "1931",
    bop:"1927",
},
{
    ques: "how many memeber in simon commission all white",
    aop: "8",
    ans: "7",
    cop: "10",
    bop:"9",
},
{
    ques: "when nehru report come",
    aop: "1930",
    ans: "1928",
    cop: "1931",
    bop:"1929",
},
{
    ques: "how many points given by jinnah to nehru report",
    aop: "10",
    ans: "14",
    cop: "13",
    bop:"20",
},
{
    ques: "who give delhi proposals",
    aop: "congress",
    ans: "muslim league",
    cop: "jinnah",
    bop:"nehru",
},
{
    ques: "who give delhi manifesto",
    ans: "congress",
    aop: "muslim league",
    cop: "jinnah",
    bop:"nehru",
},
{
    ques: "when lahore session happen",
    aop: "1930",
    ans: "1929",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when lahore 1st independance day celebrate",
    aop: "1929",
    ans: "1930",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when flag hosted on bank or ravi",
    aop: "26 jan 1930",
    ans: "31 dec 1930",
    cop: "31 jan 1928",
    bop:"30dec 1931",
},
{
    ques: "when dandi march start",
    aop: "1931",
    ans: "1930",
    cop: "1928",
    bop:"1932",
},
{
    ques: "from which date to which date dandi march start",
    aop: "13 mar to 4 apr",
    ans: "12 mar to 5 apr",
    cop: "15 mar to 6 apr",
    bop:"17 mar to 18 apr",
},
{
    ques: "how many delegate use for salt law",
    aop: "70",
    ans: "78",
    cop: "68",
    bop:"73",
},
{
    ques: "distance of dandi marhc",
    aop: "30 mile",
    ans: "40 mile",
    cop: "43 mile",
    bop:"44 mile",
},
{
    ques: "gandhi irwin pact",
    aop: "13 feb 1930",
    ans: "14 feb 1931",
    cop: "12 feb 1928",
    bop:"14 jan 1931",
},
{
    ques: "in which session purna swaraj meaning explained",
    aop: "lucknow",
    ans: "karachi",
    cop: "pune",
    bop:"lahore",
},
{
    ques: "when communal award come",
    aop: "1930",
    ans: "1932",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when bring communal award",
    aop: "br ambedkar",
    ans: "ramsay mcdonald",
    cop: "sahjanad saraswati",
    bop:"s c bose",
},
{
    ques: "in which jail poona pact happen",
    aop: "poona",
    ans: "yerwada",
    cop: "thane",
    bop:"goa",
},
{
    ques: "when poona pact happen",
    aop: "1930",
    ans: "1932",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when GOI act came",
    aop: "1934",
    ans: "1935",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when all india kishan sabha formed",
    aop: "1934",
    ans: "1936",
    cop: "1935",
    bop:"1937",
},
{
    ques: "when congress session happen in lucknow",
    aop: "1932",
    ans: "1936",
    cop: "1928",
    bop:"1931",
},
{
    ques: "when congress socialist party formed",
    aop: "1936",
    ans: "1934",
    cop: "1935",
    bop:"1931",
},
{
    ques: "when congress session happen in faizpur",
    aop: "1936",
    ans: "1937",
    cop: "1938",
    bop:"1933",
},
{
    ques: "when congress session happen in haripur gujarat",
    aop: "1934",
    ans: "1938",
    cop: "1939",
    bop:"1931",
},
{
    ques: "when national planning committe formed",
    aop: "1936",
    ans: "1938",
    cop: "1937",
    bop:"1931",
},
{
    ques: "when congress session happen in tripuri jabalpur mp",
    aop: "1934",
    ans: "1939",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when all india forward block formed",
    aop: "1934",
    ans: "1939",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when august offer come",
    aop: "1934",
    ans: "1940",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when individual satyagarh start",
    aop: "1934",
    ans: "1940",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when cripps mission come",
    aop: "1934",
    ans: "1942",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when auit india movement start",
    aop: "1934",
    ans: "1942",
    cop: "1938",
    bop:"1931",
},
{
    ques: "when formed indian national army or who formed",
    aop: "1934 mohan singh",
    ans: "1942 mohan singh",
    cop: "1938 sc bose",
    bop:"1941 sc bose",
},
{
    ques: "which is direct action day",
    aop: "16 aug 1947",
    ans: "16 aug 1946",
    cop: "15 aug 1948",
    bop:"15 aug 1949",
},
]
const modHtml = modernData.map(e =>
    `<div class="quesCol">
                    <div class="ques">${e.ques}</div>
                     <div class="op">${e.aop}</div>
                      <div class="op">${e.cop}</div>
                       <div class="ans">${e.ans}</div>
                        <div class="op">${e.bop}</div>
                    </div>
                    
                    
                    `
).join('')
const mod = document.querySelector(".modern")
mod.innerHTML = modHtml

let ans = document.querySelectorAll(".ans")
ans.forEach(e => {
    e.addEventListener("click", (i) => {
            i.target.classList.add("green")
    })

})
